version: "3.9"
services:
  nginx-rtmp:
    build: .
    container_name: nginx-rtmp
    ports:
      - "1935:1935"
      - "8080:8080"
    # 512MiB tmpfs inside container; change or bind-mount host RAM disk if needed
    tmpfs:
      - /mnt/ramdisk:rw,size=512m
    # Uncomment or pass via environment to enable pushing
    # environment:
    #   PASS_STREAM: "true"
    #   PASS_URL: "rtmp://edge.example.com/live"
    restart: unless-stopped
